name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-workflow:
    uses: .github/workflows/workflow-A.yml

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: .github/workflows/workflow-B.yml
    with:
      script: "Hello world!"
